import type { Metadata } from "next";

import { Geist, Geist_Mono, Spectral } from "next/font/google";

import { Nunito_Sans } from "next/font/google";

import "./globals.css";

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"],
});

const spectral = Spectral({
  variable: "--font-spectral",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"

      className={`${geistSans.variable} ${geistMono.variable} ${spectral.variable} h-full antialiased`}

      className={`${nunitoSans.variable} h-full antialiased`}

    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
