spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.dndeevsqdjdbveotnrkh}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:SebastianT28_$%#}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.default_schema=logistica
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true

server.port=${PORT:8080}