name: Frontend CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'backend/**'
      - 'README.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'backend/**'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run Type Check
      run: npm run typecheck

    - name: Run Unit Tests
      run: npm run test

    - name: Build Next.js
      run: npm run build
