name: K6 Stress Test

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'URL de la aplicación a probar'
        required: true
        default: 'https://erp-sunat-frontend.vercel.app'

jobs:
  stress-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run k6 stress test
      uses: grafana/k6-action@v0.3.1
      with:
        filename: performance-tests/stress-test.js
        flags: --out cloud
        token: ${{ secrets.K6_CLOUD_TOKEN }}
      env:
        TARGET_URL: ${{ github.event.inputs.target_url }}
